### PR TITLE
Fix sessions and add alpine binary creation for musl support

### PR DESCRIPTION
**Pull request by slimm609**
This resolves ECS task errors and config files as well.   I have tested this on mac, in docker and in ECS.

### CODE REVIEW

**Comment by kgilpin** [comment]
@slimm609 thanks for your contribution! Can you add a section to the README that describes this change? Honestly I need a little more context as well to understand what's being fixed.

**Comment by slimm609** [comment]
There are 2 ways to get AWS credentials.   

`session.NewSession`
gets configuration from the credentials file in ~/.aws/ directory

`session.NewSessionWithOptions`
gets configuration from a ec2 IAM role.   (http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)

The credentials are first pulled from the host from the AWS IAM role, if those credentials do not exist then it looks to the local configuration in ~/.aws/   

still getting the credentials, just supporting the AWS IAM roles.

**Comment by ryanprior** [comment]
@slimm609 thank you for submitting this!

I will be able to evaluate the PR when:
* it has a more clear description of the errors and/or problems that it's solving
* it has a section in the README explaining its behavior to users

Can you update it with those things?

**Comment by slimm609** [comment]
I'm not sure what you want me to add to the README...  

The old AWS SDK did not support IAM roles, only credentials files. 

With the update of the SDK it added support for IAM roles.  (http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)

The old way  (session.NewSession) only checked for the credentials in $HOME/.aws/credentials,  with the updated SDK it was updated to add support for the old way that was supported ($HOME/.aws/credentials) and added support for AWS IAM roles.    The way the code operates didn't change.   The change first checks for user credentials provided via the IAM roles and if they do NOT exist, then it checks for the local config file in the $HOME/.aws/  directory. 

The other change was added support for alpine docker image which uses MUSL instead of glibc.   This now builds both a linux-x86_64 and a linux-x86_64 alpine binary.   

None of this is in the README currently so I don't know where to add it.   Do you want an "Update" section added to the README?    

The change added support for the recommended way to do AWS authentication when running on an EC2 instance.

**Comment by slimm609** [comment]
In your current README you have a link to 
https://github.com/aws/aws-sdk-go#configuring-credentials

Which has 3 options 

> 
> - Environment Credentials - Set of environment variables that are useful when sub processes are created for specific roles.
> 
> - Shared Credentials file (~/.aws/credentials) - This file stores your credentials based on a profile name and is useful for local development.
> 
> - EC2 Instance Role Credentials - Use EC2 Instance Role to assign credentials to application running on an EC2 instance. This removes the need to manage credential files in production.


 This option below was not working.   This is now working 

- EC2 Instance Role Credentials - Use EC2 Instance Role to assign credentials to application running on an EC2 instance. This removes the need to manage credential files in production.

**Comment by dustinmm80** [comment]
This looks great, sorry for the delay on merge @slimm609. Merging and cutting a new release now.

**Pull request merged**
